# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password: root

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZTFmYzhiOWUzMTQ0YjQzNjEwMjBlYWJiMThjOTk3ZDM1NGIzNmI4YmNkZGZmNzVmMjIxNjA5MzM2ODMxMjI3ZWE5ZWU4N2NmZjhjMjU2OGVjYWJlMTg5YWIyZjcyZGNkMTM1YzcxOWU0ODFkMmI4MWNkNjhhOWQxZjc2MzI0YTA=
